export enum userModule {
    ROLE = 1,
    AUTH_USER = 2,
    PROFILE = 3,
    INSTITUTION = 4,
    DEPARTMENT = 5,
    COURSE = 6,
    MODULE = 7,
    MODULE_FILE = 8,
    QUIZ = 9,
    QUESTION = 10,
    ASSIGN_TEACHERS = 11,
    ENROLL_STUDENTS = 12,
    ANNOUNCEMENT = 13,
    LESSONS = 14,
}