import { commonEnv } from './environment.common';

export const environment = {
  ...commonEnv,
  production: false,
  // departmentUrl: `${commonEnv.baseUrl}/department/uhpocms`,
  // adminInstitutionUrl: `${commonEnv.baseUrl}/admininstitution/uhpocms`,
  // instituteAdminUrl: `${commonEnv.baseUrl}/instituteadmin/uhpocms`,
  // authUserUrl: `${commonEnv.baseUrl}/authuser/uhpocms`,
  // categoryUrl: `${commonEnv.baseUrl}/category/uhpocms`,
  // courseUrl: `${commonEnv.baseUrl}/course/uhpocms`,
  // courseDepartmentUrl: `${commonEnv.baseUrl}/course/uhpocms`,
  // emailUrl: `${commonEnv.baseUrl} /email/uhpocms`,
  // moduleUrl: `${commonEnv.baseUrl} /module/uhpocms`,
  // quizUrl: `${commonEnv.baseUrl} /quiz/uhpocms`,
  // adminRoleUrl: `${commonEnv.baseUrl} /adminrole/uhpocms`,
  // questionUrl: `${commonEnv.baseUrl} /question/uhpocms`,
  // announcementUrl: `${commonEnv.baseUrl} /announcement/uhpocms`,
  // moduleFileUrl: `${commonEnv.baseUrl} /modulefile/uhpocms`,
  // enrollStudentUrl: `${commonEnv.baseUrl} /enrolltostudent/uhpocms`,
  // assignCourseUrl: `${commonEnv.baseUrl} /course/uhpocms / course`,
  // syllabusUrl: `${commonEnv.baseUrl} /courseSyllabus/uhpocms / courseSyllabus`,
  // assignTeacherUrl: `${commonEnv.baseUrl} /assigntoteacher/uhpocms / assigntoteacher`,
  // accesscontrolUrl: `${commonEnv.baseUrl} /accesscontrol/uhpocms / access`,
  // answerUrl: `${commonEnv.baseUrl} /answer/uhpocms`,
  // moduleFileProgressUrl: `${commonEnv.baseUrl} /modulefileprogress/uhpocms`,
  // moduleProgressUrl: `${commonEnv.baseUrl} /moduleprogress/uhpocms`,
  // courseProgressUrl: `${commonEnv.baseUrl} /courseprogress/uhpocms`,
  // quizProgressUrl: `${commonEnv.baseUrl} /quizprogress/uhpocms`,
  // studentAnswerUrl: `${commonEnv.baseUrl} /studentquizresult/uhpocms / quizresult`,
  // accessPrivilegeUrl: `${commonEnv.baseUrl} /accessprivilege/uhpocms`,
  //

  //////////////////////////// HTTPS URLS: REFERED FROM ENVIRONMENTS.COMMON.TS /////////////////////////////////

  departmentUrl: `${commonEnv.baseHtppsUrl}/department/uhpocms`,
  adminInstitutionUrl: `${commonEnv.baseHtppsUrl}/admininstitution/uhpocms`,
  instituteAdminUrl: `${commonEnv.baseHtppsUrl}/instituteadmin/uhpocms`,
  authUserUrl: `${commonEnv.baseHtppsUrl}/authuser/uhpocms`,
  categoryUrl: `${commonEnv.baseHtppsUrl}/category/uhpocms`,
  courseUrl: `${commonEnv.baseHtppsUrl}/course/uhpocms`,
  courseDepartmentUrl: `${commonEnv.baseHtppsUrl}/course/uhpocms`,
  emailUrl: `${commonEnv.baseHtppsUrl}/email/uhpocms`,
  moduleUrl: `${commonEnv.baseHtppsUrl}/module/uhpocms`,
  quizUrl: `${commonEnv.baseHtppsUrl}/quiz/uhpocms`,
  adminRoleUrl: `${commonEnv.baseHtppsUrl}/adminrole/uhpocms`,
  questionUrl: `${commonEnv.baseHtppsUrl}/question/uhpocms`,
  announcementUrl: `${commonEnv.baseHtppsUrl}/announcement/uhpocms`,
  moduleFileUrl: `${commonEnv.baseHtppsUrl}/modulefile/uhpocms`,
  enrollStudentUrl: `${commonEnv.baseHtppsUrl}/enrolltostudent/uhpocms`,
  assignCourseUrl: `${commonEnv.baseHtppsUrl}/course/uhpocms/course`,
  syllabusUrl: `${commonEnv.baseHtppsUrl}/courseSyllabus/uhpocms/courseSyllabus`,
  assignTeacherUrl: `${commonEnv.baseHtppsUrl}/assigntoteacher/uhpocms/assigntoteacher`,
  accesscontrolUrl: `${commonEnv.baseHtppsUrl}/accesscontrol/uhpocms/access`,
  answerUrl: `${commonEnv.baseHtppsUrl}/answer/uhpocms`,
  moduleFileProgressUrl: `${commonEnv.baseHtppsUrl}/modulefileprogress/uhpocms`,
  moduleProgressUrl: `${commonEnv.baseHtppsUrl}/moduleprogress/uhpocms`,
  courseProgressUrl: `${commonEnv.baseHtppsUrl}/courseprogress/uhpocms`,
  quizProgressUrl: `${commonEnv.baseHtppsUrl}/quizprogress/uhpocms`,
  studentAnswerUrl: `${commonEnv.baseHtppsUrl}/studentquizresult/uhpocms/quizresult`,
  accessPrivilegeUrl: `${commonEnv.baseHtppsUrl}/accessprivilege/uhpocms`,
  uploadFileurl: `${commonEnv.baseHtppsUrl}/uploadfile/uhpocms/file/upload`,

};
