import { commonEnv } from './environment.common';

export const environment = {
  ...commonEnv,
  production: false,
  // departmentUrl: `${commonEnv.baseUrl}/department/uhpocms`,
  // adminInstitutionUrl: `${commonEnv.baseUrl}/admininstitution/uhpocms`,
  // instituteAdminUrl: `${commonEnv.baseUrl}/instituteadmin/uhpocms`,
  // authUserUrl: `${commonEnv.baseUrl}/authuser/uhpocms`,
  // categoryUrl: `${commonEnv.baseUrl}/category/uhpocms`,
  // courseUrl: `${commonEnv.baseUrl}/course/uhpocms`,
  // courseDepartmentUrl: `${commonEnv.baseUrl}/course/uhpocms`,
  // emailUrl: `${commonEnv.baseUrl} /email/uhpocms`,
  // moduleUrl: `${commonEnv.baseUrl} /module/uhpocms`,
  // quizUrl: `${commonEnv.baseUrl} /quiz/uhpocms`,
  // adminRoleUrl: `${commonEnv.baseUrl} /adminrole/uhpocms`,
  // questionUrl: `${commonEnv.baseUrl} /question/uhpocms`,
  // announcementUrl: `${commonEnv.baseUrl} /announcement/uhpocms`,
  // moduleFileUrl: `${commonEnv.baseUrl} /modulefile/uhpocms`,
  // enrollStudentUrl: `${commonEnv.baseUrl} /enrolltostudent/uhpocms`,
  // assignCourseUrl: `${commonEnv.baseUrl} /course/uhpocms / course`,
  // syllabusUrl: `${commonEnv.baseUrl} /courseSyllabus/uhpocms / courseSyllabus`,
  // assignTeacherUrl: `${commonEnv.baseUrl} /assigntoteacher/uhpocms / assigntoteacher`,
  // accesscontrolUrl: `${commonEnv.baseUrl} /accesscontrol/uhpocms / access`,
  // answerUrl: `${commonEnv.baseUrl} /answer/uhpocms`,
  // moduleFileProgressUrl: `${commonEnv.baseUrl} /modulefileprogress/uhpocms`,
  // moduleProgressUrl: `${commonEnv.baseUrl} /moduleprogress/uhpocms`,
  // courseProgressUrl: `${commonEnv.baseUrl} /courseprogress/uhpocms`,
  // quizProgressUrl: `${commonEnv.baseUrl} /quizprogress/uhpocms`,
  // studentAnswerUrl: `${commonEnv.baseUrl} /studentquizresult/uhpocms / quizresult`,
  // accessPrivilegeUrl: `${commonEnv.baseUrl} /accessprivilege/uhpocms`,
  //
  departmentUrl: `https://127.0.0.1:8443/department/uhpocms`,
  adminInstitutionUrl: `https://127.0.0.1:8443/admininstitution/uhpocms`,
  instituteAdminUrl: `https://127.0.0.1:8443/instituteadmin/uhpocms`,
  // instituteAdminUrl: `https://localhost:8080/uhpocms`,
  authUserUrl: `https://127.0.0.1:8443/authuser/uhpocms`,
  // authUserUrl: `https://localhost:8070/uhpocms`,
  categoryUrl: `https://127.0.0.1:8443/category/uhpocms`,
  courseUrl: `https://127.0.0.1:8443/course/uhpocms`,

  // courseUrl: `https://localhost:8080/uhpocms`,
  courseDepartmentUrl: `https://127.0.0.1:8443/course/uhpocms`,
  emailUrl: `https://127.0.0.1:8443/email/uhpocms`,
  moduleUrl: `https://127.0.0.1:8443/module/uhpocms`,
  
  quizUrl: `https://127.0.0.1:8443/quiz/uhpocms`,
  adminRoleUrl: `https://127.0.0.1:8443/adminrole/uhpocms`,
  questionUrl: `https://127.0.0.1:8443/question/uhpocms`,

  announcementUrl: `https://127.0.0.1:8443/announcement/uhpocms`,
  moduleFileUrl: `https://127.0.0.1:8443/modulefile/uhpocms`,
  enrollStudentUrl: `https://127.0.0.1:8443/enrolltostudent/uhpocms`,
  assignCourseUrl: `https://127.0.0.1:8443/course/uhpocms/course`,
  syllabusUrl: `https://127.0.0.1:8443/courseSyllabus/uhpocms/courseSyllabus`,
  assignTeacherUrl: `https://127.0.0.1:8443/assigntoteacher/uhpocms/assigntoteacher`,
  accesscontrolUrl: `https://127.0.0.1:8443/accesscontrol/uhpocms/access`,
  answerUrl: `https://127.0.0.1:8443/answer/uhpocms`,
  moduleFileProgressUrl: `https://127.0.0.1:8443/modulefileprogress/uhpocms`,
  moduleProgressUrl: `https://127.0.0.1:8443/moduleprogress/uhpocms`,
  courseProgressUrl: `https://127.0.0.1:8443/courseprogress/uhpocms`,
  quizProgressUrl: `https://127.0.0.1:8443/quizprogress/uhpocms`,
  studentAnswerUrl: `https://127.0.0.1:8443/studentquizresult/uhpocms/quizresult`,
  accessPrivilegeUrl: `https://127.0.0.1:8443/accessprivilege/uhpocms`,
};
