import { commonEnv } from './environment.common';

export const environment = {
  ...commonEnv,
  production: false,
  // departmentUrl: `${commonEnv.baseUrl}/department/uhpocms`,
  // adminInstitutionUrl: `${commonEnv.baseUrl}/admininstitution/uhpocms`,
  // instituteAdminUrl: `${commonEnv.baseUrl}/instituteadmin/uhpocms`,
  // authUserUrl: `${commonEnv.baseUrl}/authuser/uhpocms`,
  // categoryUrl: `${commonEnv.baseUrl}/category/uhpocms`,
  // courseUrl: `${commonEnv.baseUrl}/course/uhpocms`,
  // courseDepartmentUrl: `${commonEnv.baseUrl}/course/uhpocms`,
  // emailUrl: `${commonEnv.baseUrl} /email/uhpocms`,
  // moduleUrl: `${commonEnv.baseUrl} /module/uhpocms`,
  // quizUrl: `${commonEnv.baseUrl} /quiz/uhpocms`,
  // adminRoleUrl: `${commonEnv.baseUrl} /adminrole/uhpocms`,
  // questionUrl: `${commonEnv.baseUrl} /question/uhpocms`,
  // announcementUrl: `${commonEnv.baseUrl} /announcement/uhpocms`,
  // moduleFileUrl: `${commonEnv.baseUrl} /modulefile/uhpocms`,
  // enrollStudentUrl: `${commonEnv.baseUrl} /enrolltostudent/uhpocms`,
  // assignCourseUrl: `${commonEnv.baseUrl} /course/uhpocms / course`,
  // syllabusUrl: `${commonEnv.baseUrl} /courseSyllabus/uhpocms / courseSyllabus`,
  // assignTeacherUrl: `${commonEnv.baseUrl} /assigntoteacher/uhpocms / assigntoteacher`,
  // accesscontrolUrl: `${commonEnv.baseUrl} /accesscontrol/uhpocms / access`,
  // answerUrl: `${commonEnv.baseUrl} /answer/uhpocms`,
  // moduleFileProgressUrl: `${commonEnv.baseUrl} /modulefileprogress/uhpocms`,
  // moduleProgressUrl: `${commonEnv.baseUrl} /moduleprogress/uhpocms`,
  // courseProgressUrl: `${commonEnv.baseUrl} /courseprogress/uhpocms`,
  // quizProgressUrl: `${commonEnv.baseUrl} /quizprogress/uhpocms`,
  // studentAnswerUrl: `${commonEnv.baseUrl} /studentquizresult/uhpocms / quizresult`,
  // accessPrivilegeUrl: `${commonEnv.baseUrl} /accessprivilege/uhpocms`,
  //
  departmentUrl: `http://localhost:8090/department/uhpocms`,
  adminInstitutionUrl: `http://localhost:8090/admininstitution/uhpocms`,
  instituteAdminUrl: `http://localhost:8080/uhpocms`,
  authUserUrl: `http://localhost:8090/authuser/uhpocms`,
  categoryUrl: `http://localhost:8090/category/uhpocms`,
  courseUrl: `http://localhost:8090/course/uhpocms`,
  courseDepartmentUrl: `http://localhost:8090/course/uhpocms`,
  emailUrl: `http://localhost:8090/email/uhpocms`,
  moduleUrl: `http://localhost:8090/module/uhpocms`,
  quizUrl: `http://localhost:8090/quiz/uhpocms`,
  adminRoleUrl: `http://localhost:8090/adminrole/uhpocms`,
  questionUrl: `http://localhost:8090/question/uhpocms`,
  announcementUrl: `http://localhost:8090/announcement/uhpocms`,
  moduleFileUrl: `http://localhost:8090/modulefile/uhpocms`,
  enrollStudentUrl: `http://localhost:8090/enrolltostudent/uhpocms`,
  assignCourseUrl: `http://localhost:8090/course/uhpocms/course`,
  syllabusUrl: `http://localhost:8090/courseSyllabus/uhpocms/courseSyllabus`,
  assignTeacherUrl: `http://localhost:8090/assigntoteacher/uhpocms/assigntoteacher`,
  accesscontrolUrl: `http://localhost:8090/accesscontrol/uhpocms/access`,
  answerUrl: `http://localhost:8090/answer/uhpocms`,
  moduleFileProgressUrl: `http://localhost:8090/modulefileprogress/uhpocms`,
  moduleProgressUrl: `http://localhost:8090/moduleprogress/uhpocms`,
  courseProgressUrl: `http://localhost:8090/courseprogress/uhpocms`,
  quizProgressUrl: `http://localhost:8090/quizprogress/uhpocms`,
  studentAnswerUrl: `http://localhost:8090/studentquizresult/uhpocms/quizresult`,
  accessPrivilegeUrl: `http://localhost:8090/accessprivilege/uhpocms`,
};
